# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: cgr.dev
  repository: defenseunicorns.com/postgres-operator
  tag: 1.15.1
configConnectionPooler:
  connection_pooler_image: "cgr.dev/defenseunicorns.com/pgbouncer:v1.25.2"
configLogicalBackup:
  logical_backup_docker_image: "cgr.dev/defenseunicorns.com/postgres-operator-logical-backup-fips:1.15.1"
configGeneral:
  docker_image: "cgr.dev/defenseunicorns.com/spilo-17:4.1.2"
