# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pepr-pgbouncer
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pepr-pgbouncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pepr-pgbouncer
subjects:
  - kind: ServiceAccount
    name: pepr-pgbouncer
    namespace: pepr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepr-pgbouncer
  namespace: pepr-system
---
apiVersion: v1
data:
  value: >-
    Y2FiMTU5ZTVjNTg3NjkwNWVjNmY0NWMwMjY5ODIyNTRiZTI4Mzg0MWM3Mzk3NDkyYjEzZjgwZDUxZDJmNGQyYw==
kind: Secret
metadata:
  name: pepr-pgbouncer-api-path
  namespace: pepr-system
type: Opaque
---
apiVersion: v1
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDcURDQ0FaQ2dBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBQU1CNFhEVEkyTURZd05ESXdOVGsxDQpORm9YRFRJM01EWXdOREl3TlRrMU5Gb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DDQpnZ0VCQUttWjlDZlVscGdMQTZydlJTYmdsV3pGSmJCWHJJYmtqUkRPMm8zTjhSVGtwUjRuOFoxZjNNUHB1Z2oxDQpsRGRvS2JNU2kyZll0aVRmdjJ4STU0eW5YUVNVUFNlK0ZJQkk3R2x3OGJwemVDb1RkdkZ5UndMRGc4d3gva3F4DQpnRHRtbGI0Y0ZRNGs3bGpHSTFEaHA3cHRwcVJaM3hUM3BmelNMd1NCcC9xNXdqaHMzTlJ6Ukw1Vy8ybGllN3lDDQpHWGlscjU3alNKcXlIWjJQbUN2S3lpdmRGNURhSU1ITzlFYkNKak1penBjSDV1Qmx4R2lXbzljTXRyVFpqS0g4DQp2Mlk3d0xac2tXM2dGQ1VUbEw4aG9TUU9jVUpJUkVHdXlTaHo2VVJveWhtM3lxMnpacVFxRTZsbTU5WWFwcDVpDQp1dXFKMm1NSzl6RFN0eGcvTXRkRStKUEpneThDQXdFQUFhTXRNQ3N3S1FZRFZSMFJCQ0l3SUlJZWNHVndjaTF3DQpaMkp2ZFc1alpYSXVjR1Z3Y2kxemVYTjBaVzB1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRHVncHpuDQpoQTNvczZvNDlpZVN4eGthejNyNzU5L2Y5cldMWWpDRzVMNDQ2czBmMG45TEQwSWVmRHROQmxSTS8xY2ZMSDlXDQo4VUpKUWxFZjl4VlN0TzRIYXl0ZVNUZTEwd3ZRcCs4eWJ6Q1FKWjBvWDhsT0ZDa0d2NnlKaG5nZ0lxRlZuckY3DQpFTXpVN1E4ZCsydFZOWU0yMFVqQW5mSWxScHI3b2Z4cHdIWWtaRk1PblN1NDI4blRabHdMMmtUTGRTNGVuWWUvDQpZRlc5UXFOaUxSUkE1MDVOVjRFUVJmUlk5WnJ1a0lmQWNnRkVGamF0VGloMnkyeTZDVXBqejhCcFdMWGxRTThCDQo5RXFTQlNRM1ptUmszeWFCcVExeXk3cStIb3hEcHNTTXIzdHRqMTBzN3NjS28vNG5DRjR5NHM0RnN2YnBsKzIxDQpVck91anpUTVFxS3ZvNUw0DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQXFabjBKOVNXbUFzRHF1OUZKdUNWYk1VbHNGZXNodVNORU03YWpjM3hGT1NsSGlmeA0KblYvY3crbTZDUFdVTjJncHN4S0xaOWkySk4rL2JFam5qS2RkQkpROUo3NFVnRWpzYVhEeHVuTjRLaE4yOFhKSA0KQXNPRHpESCtTckdBTzJhVnZod1ZEaVR1V01ZalVPR251bTJtcEZuZkZQZWwvTkl2QklHbitybkNPR3pjMUhORQ0KdmxiL2FXSjd2SUlaZUtXdm51TkltcklkblkrWUs4cktLOTBYa05vZ3djNzBSc0ltTXlMT2x3Zm00R1hFYUphag0KMXd5MnRObU1vZnkvWmp2QXRteVJiZUFVSlJPVXZ5R2hKQTV4UWtoRVFhN0pLSFBwUkdqS0diZktyYk5tcENvVA0KcVdibjFocW1ubUs2Nm9uYVl3cjNNTkszR0Q4eTEwVDRrOG1ETHdJREFRQUJBb0lCQURWRklsOTZVZHlxcFBuRg0KRW9MT0NwRHg4VThNa3FlQjFOOEJJYnRsZ29IdCtRRGFTZlVFdlpvWmFQSFVkTHZjYnpDTU5CWW5ocnBaUHM0Nw0KcmVMTFZKZVNHZzFJRWpkaThFS0VFNkRkRU5LaWIzc1J5a1VQZE8rbmlqZ2F2V3lxNFlDbllHT2piT3VjUEU1MA0KdWhKL3kxWVcxazlISTY4ZnMxM21mWVR1WUpjSTgyWnBYRDdMSVZmMGQ1RFRVMnVWVDhzczNSd2NrRWxpVG9qYg0KMW9UL1luSkpxN0FPaUJWdEpxNTQ5RHhzU0c3cngrU2pjUnN0UXZQM0lLSDJ6ZEtiYzU1M3pMYUxxTUprL1pJRA0KQ2pmSi81OS85a1FuM3EzVkU2cGYrYUVpMkpsYld3T0VWWmJOc3dZVThmZnVOK2lJOEVJZXF2OEVnTkNEV1dJbQ0KbFc3anF3RUNnWUVBMlZ3UVJLTWE5TWc5dTBJaU5ldjVDUU5OTncxOTY2ck5DbnU4dDlsMkZTY2tqMkNDVThxTg0KZU5VV1NlUEZWd25uT0tQaUYvMDYvMHo3MjVQd3pRYmwzM3BGY2hZcDUrSStKVnJkOVhmSWQxVnBnbFN0a0g0eQ0KSVF3Z295Z1FWS2pWcXZpQWJqTjM0TDZuSlpQMXdCTjZYWUlOUHFpQithTEowQTVYZWVadEVDOENnWUVBeDhCdg0KUVRLRWJUemRKZkd5eE9hWnBLRnBLQnNGbHlhN0tzdm01M2xNZ2dKOEI5RVFWVEhqWnkrNk1TdjJidkRRUi84WA0KTldQNmVDZ29wdE1kN1NzM2Uyc0NMV3cyLzg1VTBSeWNIYzRpcHIvc1phaGFkamt6QzNvdWE3M1UxVE1XVFdRZg0KbEt0dEI5cGJhRnNSY1ZONlFoSnJ5ZndmM2RaUDhtdTBMSHdDL1FFQ2dZQThtYzV2VklwUGRRVEJFTTg0K1hHVg0KY2JZMWd5MTRaMGFEaGJ3NEJnbEdISU8wOWROZ1NUam9WNEMvV1NITUFwYlUwOXhWaytTL0NWZXZBTEJDZVluZA0KcE5sMzFYWVprSnFERDdLU25iTG1rb200TEtPM2hYZTBmdzBhY0RFZGFYVXBGZCs0MmVDeWFIVnhwSzcvdm01Lw0KWTZNTnRTMkh6RHM0SnNkODFTSFRRUUtCZ1FDNHpIQmhHZkpuK1hJRFE2dUcvR3hTWWI0ZWkzbE5rRmlDVEdmUA0KNkdsK3NmdTdZNUEvc1VyWDBORHA0dWszVS9UdFZyTkxBcmJiYVJQSzJ2QUoxZnliWXJGK0FtcVRtSGpoaVIxcA0KZWFhWExHSHczcUxxVXhyRldJRVB6bXpUM1ZLWndMSnk0WEdhWFVwSnJrN2gwRUFBVm5pQVFvL2N0UVA3bStieA0KYkwxN0FRS0JnRjFOL0NUeHVEZlJrZWEvdEs1TG41M3hpY1lkL2hiWVRjRWpxMmlnMjV3eklxSlRpNFpGVGJuTw0KMmo4RVJIRGdTbVovbjJaeHdUQmpkN2I4QlNaWDF4SXo3RXd1NU42WWo5OUNMU0UwRzdZVW5RWWpOUkFnZTRTVQ0KeWVacVVodjBXWjB6MGM1bjlpRVArLzA0MFBnZk5sMS96SXZ0SzFpNmhHMlh0NFlrWjcxaA0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg==
kind: Secret
metadata:
  name: pepr-pgbouncer-tls
  namespace: pepr-system
type: kubernetes.io/tls
---
apiVersion: v1
data:
  module-e0519630f08b84a64d74fb755b0034c2d22ba9cbbfe54c303fe5b2bd4c21bbef.js.gz: >-
    H4sIAAAAAAAAE71XbW/bNhD+3l+hcEEiATTtNFsXyFC8ttmAYs0SpOsKLEhhSqJt1hLJkpRdT9F/35GyHDkI2mEYlgS2RB6Pd88995IV1cE8uUo/scySnM24YNdaKqbtZryCPZOEArMoOZ/DNxK0ZAjXK1pULGY4k2LG55WmacHig1ET+SN5otnnimsWIsWURu1qkdTudOzXBmqeykpkTCO8YtpwKWI0IiNygrDdKJAqZV4VcFfOTKa5sl7i9fY+ZgK7YEHOjdWyYMYEO30B2CTAF5APlIRNHcyk9uJ/0oKKXMKysXPQMXBuUivBhiXbrKXOTXzbmozR8szAp5IFzzYDJuaAi3t3tnemIcOySnO7QXe4lTBxLWQO1p8nz503I9RgdySuq4rn4PqD11L8rLXUMeJzITVoW7N0IeXyd14yWdn4ZISzylhZvqUpK5xiAM8omrG49mZAsFYoRqhpMC3WdGPeeEU9QfDmDjbzkhsPcP01uQavqc0W3xLiIiuqnOW/8MIvgeOruIaNNkpgJ1qe5gPDbKXAOngO4ICxEIacFcyywEMItgdHR0F/O9OM9rcHg+WpGVA9D44HsJBW858M00CWeHQMm2vKrVdRpRDtIgAeFIBbYCy1lYHLVCE3JRM2GAgvNDAbuKcEfjFjY7Ti7jvQlUA4rXiRt8QM/DOEDRQwkTORcRdVH0R0Qp47glYi5xmP0ccfPWGd7OpiT9xRuAUkRj+QM3IKLOftvR9PQckLOCTBFc1zJ45SDQgP2BdFhYsUclfBL+hufO7IJzOqSgRbB5K8poqmvAAihl2KdTwbtCnwX6QRQbhPBtRlEbprIlx/WDARl01SYZU8bOHMvfjTaj7YRppApAEpy2lhSCf6uSA04zn5y+UoySXCPOm5UUHoCzATjWew4K2a+bpUA6cCm5hQJ+eaaIg6mBcO0XCOjxE6jjACxwEvDYTUYooOaxuKqEGBf2Lw9GzamHCGkXbx0++7i6JxGUpCyTsG5tqIvDGvPUHzK/1e5e4hhEXxWwdJqCLygduFWwiziNwwQDCDLAmp2YgsEMm5t5Ul4B61dDKpmzGfhQeMOOcctPf38KKoMa4URbUkb+WcrKkW4fSwzprA57GYB538sJMdB2bJlYK9aedp0+LyqprNAPGZlmX4cBFGKTXsxfcoIla+sxoOhqiyszMUYf3oTHfHV86MqUvGcIQl+fXMRADbkot8h9xLpQpgZsksdY63NSXmD2yKFZZrwfQNg3shhRy9aqr4H11jWEHSOZUxanW2TIwF6XQS75Ursb01eHUNylEbCBgfnOC0kNnyyl114WqR031w0kCNNN6fC28d6rhG7BeL4llosY4a4HgbDy5mMpzqLrp5cFjzJnBgBS5I02jbBGnSr/abPpnbrtmj8goo2ZFjQoxi2YRAqQIuW9a+t0wBgrzUmm4IN/4bwuMcpNB5tInu7/uvpICWZBdJkoyilhJjRlayqAD0ZPc0mbgS3r0RI4G8PpMcoHCWeq3dtqrMYltiKFZaupmB5XFtZKXbqLWuXVK1jfIGQ9kr3Q502F5dAhg5woraxePFxnWZ2vg476iyp2QvPlsde2tOBfxF4zYH+qjcju7GduvPJdxqTbL/6gHZX3oalUcye9CUbu3aGzZkNhv2iAA1JL8SxcZPS3BRJssShpLkFg0ro4cpF33pR8eH+1DdQeFaYURdfl37KnvtWviudF3seuA/L19+2gi9Tp5Rx06wIk8HD+2gaykRuayg17LQVTZgMLmha0f+HavX32Z1S8x/TezJwUl8EO6ROXoqWoDTGmZXxnLzSkoL2U7V/4bS1xpBV6sm3tYxOzpyoB0dhU9X1L6pT1dV1q+qUNcAZJhGtqDHPWkqhLTecjd/PPCqmyyH6Q6oGLoPlEZGhFyHUTNt3A+uYarO2qF/rzLuzimojUq7qQby0rWt7TTem8wOawYF05HGDTI5uYbLL/1wHRb4trqLxs+Gw++CtrxAUXEd7v3N22T/PwiSfTKkpOrZ35rdzkvLDAAA
kind: Secret
metadata:
  name: pepr-pgbouncer-module
  namespace: pepr-system
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pepr-pgbouncer-store
  namespace: pepr-system
rules:
  - apiGroups:
      - pepr.dev
    resourceNames:
      - ''
    resources:
      - peprstores
    verbs:
      - create
      - get
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pepr-pgbouncer-store
  namespace: pepr-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pepr-pgbouncer-store
subjects:
  - kind: ServiceAccount
    name: pepr-pgbouncer-store
    namespace: pepr-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    pepr.dev/description: >-
      Configures the distroless pgbouncer connection pooler for the Zalando postgres-operator
  labels:
    app: pepr-pgbouncer-watcher
    pepr.dev/controller: watcher
    pepr.dev/uuid: pgbouncer
  name: pepr-pgbouncer-watcher
  namespace: pepr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pepr-pgbouncer-watcher
      pepr.dev/controller: watcher
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        buildTimestamp: '1780606793952'
      labels:
        app: pepr-pgbouncer-watcher
        pepr.dev/controller: watcher
    spec:
      containers:
        - args:
            - /app/node_modules/pepr/dist/controller.js
            - e0519630f08b84a64d74fb755b0034c2d22ba9cbbfe54c303fe5b2bd4c21bbef
          env:
            - name: PEPR_WATCH_MODE
              value: 'true'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: info
          image: ghcr.io/defenseunicorns/pepr/private/controller:v1.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          name: watcher
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 200m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/certs
              name: tls-certs
              readOnly: true
            - mountPath: /app/load
              name: module
              readOnly: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: pepr-pgbouncer
      terminationGracePeriodSeconds: 5
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-pgbouncer-tls
        - name: module
          secret:
            secretName: pepr-pgbouncer-module
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    pepr.dev/description: >-
      Configures the distroless pgbouncer connection pooler for the Zalando postgres-operator
  labels:
    app: pepr-pgbouncer
    pepr.dev/controller: admission
    pepr.dev/uuid: pgbouncer
  name: pepr-pgbouncer
  namespace: pepr-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepr-pgbouncer
      pepr.dev/controller: admission
  template:
    metadata:
      annotations:
        buildTimestamp: '1780606793952'
      labels:
        app: pepr-pgbouncer
        pepr.dev/controller: admission
    spec:
      containers:
        - args:
            - /app/node_modules/pepr/dist/controller.js
            - e0519630f08b84a64d74fb755b0034c2d22ba9cbbfe54c303fe5b2bd4c21bbef
          env:
            - name: PEPR_WATCH_MODE
              value: 'false'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: info
          image: ghcr.io/defenseunicorns/pepr/private/controller:v1.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          name: server
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 200m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/certs
              name: tls-certs
              readOnly: true
            - mountPath: /app/api-path
              name: api-path
              readOnly: true
            - mountPath: /app/load
              name: module
              readOnly: true
      priorityClassName: system-node-critical
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: pepr-pgbouncer
      terminationGracePeriodSeconds: 5
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-pgbouncer-tls
        - name: api-path
          secret:
            secretName: pepr-pgbouncer-api-path
        - name: module
          secret:
            secretName: pepr-pgbouncer-module
---
apiVersion: v1
kind: Service
metadata:
  labels:
    pepr.dev/controller: admission
  name: pepr-pgbouncer
  namespace: pepr-system
spec:
  ports:
    - port: 443
      targetPort: 3000
  selector:
    app: pepr-pgbouncer
    pepr.dev/controller: admission
---
apiVersion: v1
kind: Service
metadata:
  labels:
    pepr.dev/controller: watcher
  name: pepr-pgbouncer-watcher
  namespace: pepr-system
spec:
  ports:
    - port: 443
      targetPort: 3000
  selector:
    app: pepr-pgbouncer-watcher
    pepr.dev/controller: watcher
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pepr-pgbouncer
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlOakEyTURReU1EVTVOVE5hRncweU56QTJNRFF5TURVNU5UTmFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEdnVPZ3FVaW90b3ZlMXRWWjl0R1p4DQo4TnBqUGs3QXVSWmhZTDJOQ1Z1bW9jbU9zY0syQXMwOHhOZkQzWmYxMURDaCtmaXRMMEo2MkUzTEkvOFBQOG02DQp5anRVSkt0TVV1Y3p4ZkVyKzNacjZxYWZHV1AwcjFXeTNCZkt3eDd2cFVKM1E5d2xyaXdpWS83Q0ZIMzJ5eWxUDQo5Z3VwRWhKdkY4clRTSHBxRktLcG52V0x3YlViSTdmYld4dVdOSktaYXVEbGlUU0hjTHpJbUtVN1g3aGJxcEVMDQp2SW1OaGQ4UXIzd1J4Z3p0TzhlNmpNZE9KYk94Qi9iTHJHS2VYSS9yL1laQTJXUXdQYmtaR0o1NVIvREkxZTJCDQpINUVhWWdTMEpPVk9GclFPQmlTaGo1TFNPcjlTYkxGblFScFJNRThHQlJVRTg2N3FBcllxcyt2VjdOZlMwODV0DQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQkduMHgvaTczaWRlYlBaKzhsQ282bGdNUXdyelJGUXRPdGs1eVZKYUJRdHU5RjAwNk1sSmRxDQpCby9KdHZiNkpmaWxxVGFxZ1dMTDNCalFGT1hyczRvenRmMk1ic2ZpWm1CbUQwZmFTMTVtN0hHWWlxY0M2VjdaDQpNdkdhSGNDQmZCQjBsT0Z2aFFkSXVtUXpBZVEyZWJERHVjUisyYXh4RWI4Q1NhRzI2UUtzYVNjQnZVNjhXTmQwDQp6SDcvYkVEU3E2aXJucjVOc05YT05DaDBvR2Rwb3k3VHdtR3puc09aSFpuT2dlb3A2K0dRV1RkZjNvNmU4bXd3DQpJNExuMmNObGxSSEFpek5YR1F5Y0hPTkZDb0F3M0JmNkp3Zms4VXc4VVRwcXYxRnhpUHN2aVdpZnNLTllzOE9aDQpZR1YxcVBZTjcyQ1NSalFXdUhWOUl5SjVMeXkxQWlLcQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: pepr-pgbouncer
        namespace: pepr-system
        path: >-
          /mutate/cab159e5c5876905ec6f45c026982254be283841c7397492b13f80d51d2f4d2c
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: pepr-pgbouncer.pepr.dev
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
    sideEffects: None
    timeoutSeconds: 10
