# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pepr-pgbouncer
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pepr-pgbouncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pepr-pgbouncer
subjects:
  - kind: ServiceAccount
    name: pepr-pgbouncer
    namespace: pepr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepr-pgbouncer
  namespace: pepr-system
---
apiVersion: v1
data:
  value: >-
    OGY0Zjk4YzA5MWFhOTA4ZTRiNGZiMDhiNzY0NjcyZWE4ZGM0NmMzNmJmMmM5N2QyYWQwY2U5ODlmMjcwNTQ4Yg==
kind: Secret
metadata:
  name: pepr-pgbouncer-api-path
  namespace: pepr-system
type: Opaque
---
apiVersion: v1
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDcURDQ0FaQ2dBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBQU1CNFhEVEkyTURZd05ESXdOVFl4DQpNbG9YRFRJM01EWXdOREl3TlRZeE1sb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DDQpnZ0VCQUpRZTFtbW9xZFdEZnpnUlU3T1NkUC95Qm4xcjFKQ1A4akx5RXlWWlZSbGU4Q3M3b0o4S2E0MGFxbDA2DQp3ZTdrTy9qR2c1M1N6NUMva0NjZDluU2I3bTRaa2RGMkpSNWR2eWY5R3hvNzdxajB6MGR2S2p1bGRtK3VPcHZHDQoveHM5ZGxUTVNxb1JQWTR0QnpObzFkN1YxNVBMTVF3bXFZZm5RZjRHNkh5Ukd6bFl2ZWtqdWhDb2VjbDZmQWhBDQo0cVB4bGxJdnpDK0JQbnNCb1NnNGZRdzV6TXFZTStzT2srSVBDWVZkOStkcFNWV1JBcDhobTdCY1c1N0NxdDVUDQpJTVgyTEFISWxCK1BMcnppY2xpMGdCREhhcDQ5SmJsNTFhUE9pQUZDSUFPb1paZWtzQUg4VEQ5cEd1VlBJNGgxDQpoejB4NWFPQWhqRjRUNGdTOHUveFc0dGExaUVDQXdFQUFhTXRNQ3N3S1FZRFZSMFJCQ0l3SUlJZWNHVndjaTF3DQpaMkp2ZFc1alpYSXVjR1Z3Y2kxemVYTjBaVzB1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjVPcG5FDQpzZXpEK2wwNjVTSzZjOTlKL1RTSW1iTnZMaVJ1YkUxM20zbmw4YlUxZSt6djFpb0M0VWZhOG5KZzZsNllKeEg5DQpxb05UOUdYTDMzZnVtSzhrdmM3VkNJVEs3WG5NSkttaHdRZ3EyT3B3YXR3RW1XVDJscG9TT2MrVjFtS2xZVjR1DQpCTEovQVZnczRyVm1ybFR1aTE1TmRPano5clZ0WGlWRGw2eVpaUVlEVW9hUk10YXNHckFhZEpUdE1OQ3NRTmpvDQpIVEZua210ZWZPeS9wSUU3VForc1dFeE41ZjJ1SENnOFljRjd1ZXlkYTc1LzRkL0ZpU3UyY29vcW1xS2RkaG9nDQozMUJqbGF3V2dxUVFqSW02SmY3RFJrdGtCd1krckFjMmM0a2h3N1FyVlRRVGpPcVp1M2o4TlNHWHRVLzhhYllzDQovWTFTZDRrUlMrY04xQUllDQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW9nSUJBQUtDQVFFQWxCN1dhYWlwMVlOL09CRlRzNUowLy9JR2ZXdlVrSS95TXZJVEpWbFZHVjd3S3p1Zw0KbndwcmpScXFYVHJCN3VRNytNYURuZExQa0wrUUp4MzJkSnZ1YmhtUjBYWWxIbDIvSi8wYkdqdnVxUFRQUjI4cQ0KTzZWMmI2NDZtOGIvR3oxMlZNeEtxaEU5amkwSE0yalYzdFhYazhzeERDYXBoK2RCL2dib2ZKRWJPVmk5NlNPNg0KRUtoNXlYcDhDRURpby9HV1VpL01MNEUrZXdHaEtEaDlERG5NeXBnejZ3NlQ0ZzhKaFYzMzUybEpWWkVDbnlHYg0Kc0Z4Ym5zS3EzbE1neGZZc0FjaVVINDh1dk9KeVdMU0FFTWRxbmowbHVYblZvODZJQVVJZ0E2aGxsNlN3QWZ4TQ0KUDJrYTVVOGppSFdIUFRIbG80Q0dNWGhQaUJMeTcvRmJpMXJXSVFJREFRQUJBb0lCQUFUVFNGcmkwcjJRN2hrTw0KZjNLUEo5NmFyTmx6Sk5hY3llQWRBTUNydTFqN1BjbTZ4STNKMGgwanJEOGpSZVFaYlZhNmFObEFYK0N3VE9ycA0KVC9rV2gxcnczRTQ5a2hIK0xkY0lxTlJlOVhSdG5UOFBnUW0yWnpoV0xiU2JjLzRZTDMydHRoVDZRTTRiNjJzaQ0KVkMxUlBCZWxlL0NRWmQ5MmlqRFRXc21NRkozMm1IQnRTMHJDc2F6dFE0L2ZiSUJjR2pYNGRJSmR2WlBUTFd2TQ0KdWtlKzZwY1orTWtuRXF0NndqUy9MSHpUeXBPWEFVQko4eUhMZk9vUDg5RXlEV2d0OFdMTWpsODFvRk10ZHo5Sg0KMTlUQjJnbGFlTlJPZzFmazk3Y1lYVjFmU2lPbFZldGRUUnZqeTlENHEwajBWWTlnYnFHWjdtaXU5VlhoU09sQg0KS1AxSTJWRUNnWUVBeHg1MC84M0lLM1dYN0NaUTVnemNYTTVHUnhGWXdROFhzd0V6OVJNS3RKTzJSRFc5aHBOWA0KaENOQnlqc3l2ZlArLy9QMGlqajMvQkxkT3dSTnVMV05NdjBKYW1LT0VueVZBeXZoUmxCTnEybzNNeHBPaEcxeQ0KZktnTklxQTh1VEsySlJGZkR3MFdnUUU1UHpldExFN0VJUFN2TlJXUEJOWDdJVS8zcDdIMGRCMENnWUVBdm03ZA0KdzdvdlJaNjJ2TlMvM0FCb2ZidTFiRkdSYWlzeG10SDhmT0tlTlJ3VGVLQlpsaXljc3lCNXpCR2UwSVY0K0JUbw0KeW9Nd1A3U1Blb0Z0RGFCKzJRalVteFB2eDU3dkJGNDNOby96bUxCT0hBUVcydStUMlByemR6Nm1teUt2dzVKWA0KWlpVRVZtbGM5eStkUDBTRnY2U080ek45SWs1L0ZVNnJuVURtQXRVQ2dZQUY2K3owMG96YVpnUGZuUUFZNTFjQw0KVjR3VmZ2bVJ2RDRyTDZUNDY5a01wN3ZxNldJNmgxVTU4OFo0R2l5WEk1TjR6eXQ5bE5ZakkvaDZVZFZ4NGN4Uw0KTU40LzBMQ0M4anVJUFp6VWQzem4xUi9SSUQ0bmlBMjRrVkxhcmNOQWlyYUtBYXMvQ2xlWi9JeFVTZmFYYzd3Mw0KY3E5bk43M3FHZWIvQlo3SzJPcjVMUUtCZ0MvR3JNaUFHNEFCODZLb1ZZSWljQlNyVlRiWnQvdkUzbXNUSjU5Rg0KVTUvTGJXOGorNVhibDJ5eFJ4MVZobHlXUCtVdGljSFU2L1B2bnRlRFJSTFlJenJjSmtySjA2eG5TVnYxTHpEMw0KS0l3MEgwU1VHZy9QYjI1T2QycUJRMWRFZW9nOFhNVFZnQU1WNkFiejRTV1FVV1hsS1J3RFBPK3dkZDJvb1JHUQ0KeUtRSkFvR0FEYjFQcWQwNi9JUVNrVjZPUHE5K3I4bWxYODd5cy9hc3ZXTlZzMlVxc1o5VFg1Q09XOUh2Q2NReg0KTk1DMEhpaXN0c3d0SmZLMCtxajM2bVhKNVRwZ1h4OUdDaWRIdVk3M1ZLNU91azZ6b2E1dzRqQVQwK09BTllVbg0KUTljM3FTcUFaV2QzKzg3R3RyYWN5eUVZK2tIRi91VElnQWJyckhyYUwyQVZOSFFnczZjPQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg==
kind: Secret
metadata:
  name: pepr-pgbouncer-tls
  namespace: pepr-system
type: kubernetes.io/tls
---
apiVersion: v1
data:
  module-e0519630f08b84a64d74fb755b0034c2d22ba9cbbfe54c303fe5b2bd4c21bbef.js.gz: >-
    H4sIAAAAAAAAE71XbW/bNhD+3l+hcEEiATTtNFsXyFC8ttmAYs0SpOsKLEhhSqJt1hLJkpRdT9F/35GyHDkI2mEYlgS2RB6Pd88995IV1cE8uUo/scySnM24YNdaKqbtZryCPZOEArMoOZ/DNxK0ZAjXK1pULGY4k2LG55WmacHig1ET+SN5otnnimsWIsWURu1qkdTudOzXBmqeykpkTCO8YtpwKWI0IiNygrDdKJAqZV4VcFfOTKa5sl7i9fY+ZgK7YEHOjdWyYMYEO30B2CTAF5APlIRNHcyk9uJ/0oKKXMKysXPQMXBuUivBhiXbrKXOTXzbmozR8szAp5IFzzYDJuaAi3t3tnemIcOySnO7QXe4lTBxLWQO1p8nz503I9RgdySuq4rn4PqD11L8rLXUMeJzITVoW7N0IeXyd14yWdn4ZISzylhZvqUpK5xiAM8omrG49mZAsFYoRqhpMC3WdGPeeEU9QfDmDjbzkhsPcP01uQavqc0W3xLiIiuqnOW/8MIvgeOruIaNNkpgJ1qe5gPDbKXAOngO4ICxEIacFcyywEMItgdHR0F/O9OM9rcHg+WpGVA9D44HsJBW858M00CWeHQMm2vKrVdRpRDtIgAeFIBbYCy1lYHLVCE3JRM2GAgvNDAbuKcEfjFjY7Ti7jvQlUA4rXiRt8QM/DOEDRQwkTORcRdVH0R0Qp47glYi5xmP0ccfPWGd7OpiT9xRuAUkRj+QM3IKLOftvR9PQckLOCTBFc1zJ45SDQgP2BdFhYsUclfBL+hufO7IJzOqSgRbB5K8poqmvAAihl2KdTwbtCnwX6QRQbhPBtRlEbprIlx/WDARl01SYZU8bOHMvfjTaj7YRppApAEpy2lhSCf6uSA04zn5y+UoySXCPOm5UUHoCzATjWew4K2a+bpUA6cCm5hQJ+eaaIg6mBcO0XCOjxE6jjACxwEvDYTUYooOaxuKqEGBf2Lw9GzamHCGkXbx0++7i6JxGUpCyTsG5tqIvDGvPUHzK/1e5e4hhEXxWwdJqCLygduFWwiziNwwQDCDLAmp2YgsEMm5t5Ul4B61dDKpmzGfhQeMOOcctPf38KKoMa4URbUkb+WcrKkW4fSwzprA57GYB538sJMdB2bJlYK9aedp0+LyqprNAPGZlmX4cBFGKTXsxfcoIla+sxoOhqiyszMUYf3oTHfHV86MqUvGcIQl+fXMRADbkot8h9xLpQpgZsksdY63NSXmD2yKFZZrwfQNg3shhRy9aqr4H11jWEHSOZUxanW2TIwF6XQS75Ursb01eHUNylEbCBgfnOC0kNnyyl114WqR031w0kCNNN6fC28d6rhG7BeL4llosY4a4HgbDy5mMpzqLrp5cFjzJnBgBS5I02jbBGnSr/abPpnbrtmj8goo2ZFjQoxi2YRAqQIuW9a+t0wBgrzUmm4IN/4bwuMcpNB5tInu7/uvpICWZBdJkoyilhJjRlayqAD0ZPc0mbgS3r0RI4G8PpMcoHCWeq3dtqrMYltiKFZaupmB5XFtZKXbqLWuXVK1jfIGQ9kr3Q502F5dAhg5woraxePFxnWZ2vg476iyp2QvPlsde2tOBfxF4zYH+qjcju7GduvPJdxqTbL/6gHZX3oalUcye9CUbu3aGzZkNhv2iAA1JL8SxcZPS3BRJssShpLkFg0ro4cpF33pR8eH+1DdQeFaYURdfl37KnvtWviudF3seuA/L19+2gi9Tp5Rx06wIk8HD+2gaykRuayg17LQVTZgMLmha0f+HavX32Z1S8x/TezJwUl8EO6ROXoqWoDTGmZXxnLzSkoL2U7V/4bS1xpBV6sm3tYxOzpyoB0dhU9X1L6pT1dV1q+qUNcAZJhGtqDHPWkqhLTecjd/PPCqmyyH6Q6oGLoPlEZGhFyHUTNt3A+uYarO2qF/rzLuzimojUq7qQby0rWt7TTem8wOawYF05HGDTI5uYbLL/1wHRb4trqLxs+Gw++CtrxAUXEd7v3N22T/PwiSfTKkpOrZ35rdzkvLDAAA
kind: Secret
metadata:
  name: pepr-pgbouncer-module
  namespace: pepr-system
type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pepr-pgbouncer-store
  namespace: pepr-system
rules:
  - apiGroups:
      - pepr.dev
    resourceNames:
      - ''
    resources:
      - peprstores
    verbs:
      - create
      - get
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pepr-pgbouncer-store
  namespace: pepr-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pepr-pgbouncer-store
subjects:
  - kind: ServiceAccount
    name: pepr-pgbouncer-store
    namespace: pepr-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    pepr.dev/description: >-
      Configures the distroless pgbouncer connection pooler for the Zalando postgres-operator
  labels:
    app: pepr-pgbouncer-watcher
    pepr.dev/controller: watcher
    pepr.dev/uuid: pgbouncer
  name: pepr-pgbouncer-watcher
  namespace: pepr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pepr-pgbouncer-watcher
      pepr.dev/controller: watcher
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        buildTimestamp: '1780606572134'
      labels:
        app: pepr-pgbouncer-watcher
        pepr.dev/controller: watcher
    spec:
      containers:
        - args:
            - /app/node_modules/pepr/dist/controller.js
            - e0519630f08b84a64d74fb755b0034c2d22ba9cbbfe54c303fe5b2bd4c21bbef
          env:
            - name: PEPR_WATCH_MODE
              value: 'true'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: info
          image: ghcr.io/defenseunicorns/pepr/private/controller:v1.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          name: watcher
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 200m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/certs
              name: tls-certs
              readOnly: true
            - mountPath: /app/load
              name: module
              readOnly: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: pepr-pgbouncer
      terminationGracePeriodSeconds: 5
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-pgbouncer-tls
        - name: module
          secret:
            secretName: pepr-pgbouncer-module
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    pepr.dev/description: >-
      Configures the distroless pgbouncer connection pooler for the Zalando postgres-operator
  labels:
    app: pepr-pgbouncer
    pepr.dev/controller: admission
    pepr.dev/uuid: pgbouncer
  name: pepr-pgbouncer
  namespace: pepr-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepr-pgbouncer
      pepr.dev/controller: admission
  template:
    metadata:
      annotations:
        buildTimestamp: '1780606572134'
      labels:
        app: pepr-pgbouncer
        pepr.dev/controller: admission
    spec:
      containers:
        - args:
            - /app/node_modules/pepr/dist/controller.js
            - e0519630f08b84a64d74fb755b0034c2d22ba9cbbfe54c303fe5b2bd4c21bbef
          env:
            - name: PEPR_WATCH_MODE
              value: 'false'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: info
          image: ghcr.io/defenseunicorns/pepr/private/controller:v1.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          name: server
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
            initialDelaySeconds: 10
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 200m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/certs
              name: tls-certs
              readOnly: true
            - mountPath: /app/api-path
              name: api-path
              readOnly: true
            - mountPath: /app/load
              name: module
              readOnly: true
      priorityClassName: system-node-critical
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: pepr-pgbouncer
      terminationGracePeriodSeconds: 5
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-pgbouncer-tls
        - name: api-path
          secret:
            secretName: pepr-pgbouncer-api-path
        - name: module
          secret:
            secretName: pepr-pgbouncer-module
---
apiVersion: v1
kind: Service
metadata:
  labels:
    pepr.dev/controller: admission
  name: pepr-pgbouncer
  namespace: pepr-system
spec:
  ports:
    - port: 443
      targetPort: 3000
  selector:
    app: pepr-pgbouncer
    pepr.dev/controller: admission
---
apiVersion: v1
kind: Service
metadata:
  labels:
    pepr.dev/controller: watcher
  name: pepr-pgbouncer-watcher
  namespace: pepr-system
spec:
  ports:
    - port: 443
      targetPort: 3000
  selector:
    app: pepr-pgbouncer-watcher
    pepr.dev/controller: watcher
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pepr-pgbouncer
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlOakEyTURReU1EVTJNVEphRncweU56QTJNRFF5TURVMk1USmFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDamJ3akdmTWx1OHg5SHZjd293WERQDQptRWNLUFBObzNaejlXVlZKRVdpSEMwZVRLcGM0S2diS1Z2V2M2Tk1DbjQxZHR6NUE2b0RVTTJCMFBiV1N6THlKDQo5bm8zM0FUWVJ6VlpGbHE3OHNxeTNUeVhZbzhJSGwxZmNDdnArTGN6OERrWUF0K3Urcjhlbzd4NU9aa00zdkQwDQpFMXhTYVNCaGMrT0VOK3luaFd5VkVFMTJXVHBURHByZ1IxZFE2RURSWmlvL0dxc0tRcE5YeFluMy9yTlVVL2pnDQpZa0NjbGN5Nm03NGlHTU5lcTRxT3JxZllEdmo0UHBBNUFaN09uWndTa3gzZUdNZTRGVjJSOWhESG9GTDE4eGVVDQpMUkhuTExMU0d1YjMxcEszQVdjQnlLUExGaGk4ay9QQyt2WDZBL0NMRGlnUmJwMS90UHNWdDdMejlxT3Z4MGVMDQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQjNUbjN6QjJxSmlvQWRBdnFUV2piSDIwTnRDeE5qTnQxT2g3UFBmSGVLMmxGZ2hrZm80RjZIDQp4YjZOSG5Venl2UndIbjkrMFVzSll5UEt0bVl1UkxrTWVwT3JzM3NtcEVoa1ZEVkcyaGlyWnptd2pHeExNLzBZDQpkdFpKYXRMNEtFZ1g2ZE9sb1hRQWV6b0ZuejRQb25zQVQ0NU1kTXlWUURlZGt4Qy9FSUc1S0dkSXljSlh4dGdpDQorZ3lUSkVMMEZyTXpic2pyL3pONCsxSkFGVzZwOUxDQ09kYzgzT2lJbW9NK25vSFltSXlNZTFJUG9oWXNHZFlMDQowTjhyc29Ka3ZuYU5MQ2J3Ui9Xbmg4dmFtWk1ubXVXUDZLbmpBME1xLzJZZnBmMm1RcDNtM2Rlb1hIUXVXSGhvDQpNejkwYTQ2N3lndHZiMTlIc2JDSTZTZHl5eUFhTkZkVQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: pepr-pgbouncer
        namespace: pepr-system
        path: >-
          /mutate/8f4f98c091aa908e4b4fb08b764672ea8dc46c36bf2c97d2ad0ce989f270548b
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: pepr-pgbouncer.pepr.dev
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
    sideEffects: None
    timeoutSeconds: 10
