# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-exporter-pod-monitor
  namespace: postgres
  labels:
    {{- include "postgres-crd-metrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      application: spilo
  podTargetLabels:
    - cluster_name
    - spilo_role
    - team
  podMetricsEndpoints:
    - port: exporter
      path: /metrics
      {{- if .Values.podMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.podMonitor.relabelings | nindent 8 }}
      {{- end }}
{{- end }}
