# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: postgres-operator
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.monitoring.enabled }}
  monitor:
    - selector:
        application: spilo
      portName: exporter
      targetPort: 9187
      kind: {{ .Values.monitoring.kind | default "PodMonitor"}}
      description: "Postgres Exporter Port"
  {{- end }}
  network:
    serviceMesh:
      mode: {{ if .Values.ambient }}ambient{{ else }}sidecar{{ end }}
    allow:
      {{- if .Values.postgresql.enabled }}
      - direction: Egress
        selector:
          app.kubernetes.io/name: postgres-operator
        remoteNamespace: postgres
        remoteSelector:
          cluster-name: pg-cluster
      {{- end }}

      - direction: Egress
        selector:
          app.kubernetes.io/name: postgres-operator
        remoteGenerated: KubeAPI

      - direction: Egress
        selector:
          app.kubernetes.io/name: postgres-crd-metrics
        remoteGenerated: KubeAPI

      # Custom rules for additional networking access
      {{- with .Values.additionalNetworkAllow }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
